# Generated by Django 3.2.9 on 2023-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='projects/static/projects/img/')),
                ('github_url', models.URLField(default='github_url', max_length=250)),
                ('medium_url', models.URLField(default='medium_url')),
            ],
        ),
    ]
